config/routes.rb
Air::Application.routes.draw do

  resources :reservations, only: [:create, :destroy]

  resources :users, except: [:index]

  get 'cities' => "pages#cities"
  get "help" => 'pages#help'

  resources :flights, only: [:index]

  root 'flights#index'

  get 'sessions/new' => 'sessions#new', as: "new_session"
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations

  validates :distance, numericality: { greater_than: 0 }

  before_validation :determine_distance

  def determine_distance
    self.distance = MileageCalculator.miles_between(self.departure_code, self.arrival_code)
  end

end

app/models/mileage_calculator.rb
class MileageCalculator

  AIRPORT_CODES = %w(ORD JFK SFO MDW)

  CHART = {
    "ORD JFK" => 740,
    "ORD LAX" => 1744,
    "ORD SFO" => 1846,
    "MDW JFK" => 740,
    "MDW LAX" => 1744,
    "MDW SFO" => 1846,
    "JFK LAX" => 2475,
    "JFK SFO" => 2586,
    "LAX SFO" => 338
  }

  def self.miles_between(departure_airport, arrival_airport)
    miles = CHART["#{departure_airport.upcase} #{arrival_airport.upcase}"]
    miles ||= CHART["#{arrival_airport.upcase} #{departure_airport.upcase}"]
    miles ||= 0
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :flight
  belongs_to :user

  after_create :update_miles_earned, :book_res_seats
  after_destroy :cancel_res_seats

  def update_miles_earned
    self.user.miles_earned += self.flight.distance
    self.user.save
  end

  # Decreases seat count for flight when reservation is booked by user.
  def book_res_seats
    self.flight.seats -= 1
    self.flight.save
  end

   # Increases seat count for flight when reservation is cancelled by user.
  def cancel_res_seats
    self.flight.seats += 1
    self.flight.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :flights, through: :reservations

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(:id => session[:user_id])
  end
  helper_method :current_user
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @flights = Flight.order('departs_at')
    @reservation = Reservation.new

    if params[:departs_from]
      @flights = @flights.where('departure_code = ?', params[:departs_from])
    end

    if params[:departs_on]
      @flights = @flights.where('DATE(departs_at) = ?', params[:departs_on])
    end

    @flights = @flights.limit(50)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def cities
  end

  def help
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to root_url, notice: 'Reservation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reservation }
      else
        format.html { render action: 'new' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to root_url, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to user_url(current_user), notice: 'Reservation was successfully cancelled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :flight_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by email: params[:email]

    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = 'Signed in successfully'
      redirect_to root_url
    else
      flash.now[:error] = "Incorrect email address or password."
      render 'new'
    end
  end

  def destroy
    reset_session
    flash[:notice] = 'Signed out successfully'
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_user_must_be_user, only: [:show, :edit, :update, :destroy]

    # Ensuring that current user cannot spoof as another user
    def current_user_must_be_user
      unless current_user == @user
        redirect_to :back, notice: "You are not authorized to do that."
      end
    end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def challenge(text)
    content_tag :li do
      concat content_tag(:span, "Challenge", class: 'label label-default')
      concat text
    end
  end

  def user_story(persona, text)
    item = "As a #{persona}, #{text}"
    content_tag :li do
      concat content_tag(:span, "User Story", class: 'label label-success')
      concat item
    end
  end

  def business_rule(text)
    content_tag(:li) do
      concat content_tag(:span, "Business Rule", class: 'label label-primary')
      concat text
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flights/edit.html.erb
<h1>Editing Flight #<%= @flight.id %></h1>


<%= form_tag(flight_url(@flight), method: 'patch') do %>

  <div>
    <%= label_tag :departs_at %><br />
    <%= datetime_select_tag :departs_at, @flight.departs_at %>
  </div>

  <div>
    <%= label_tag :departure_code %><br />
    <%= text_field_tag :departure_code, @flight.departure_code %>
  </div>

  <div>
    <%= label_tag :arrival_code %><br />
    <%= text_field_tag :arrival_code, @flight.arrival_code %>
  </div>

  <div>
    <%= label_tag :seats %><br />
    <%= number_field_tag :seats, @flight.seats %>
  </div>

  
  <div>
    <%= submit_tag "Update Flight" %>
  </div>

<% end %>

app/views/flights/index.html.erb
<div class="page-header">
  <h1>Flight Schedule</h1>

    <%= form_tag flights_url, method: 'get', id: 'flight-search' do %>
      <div>
        <%= label_tag :departs_from, 'Display flights departing from:' %>
        <%= select_tag :departs_from, options_for_select(MileageCalculator::AIRPORT_CODES) %>
        <%= label_tag :departs_on, 'departing on:' %>
        <%= text_field_tag :departs_on, Date.today, placeholder: 'Pick date...' %>
        <%= button_tag 'Go', class: 'btn btn-success btn-small' %>
      </div>
    <% end %>

</div>

<div class="row">
  <div class="col-md-12">
    <table class='table table-striped'>
      <thead>
        <tr>
          <th>Flight #</th>
          <th>Departs at</th>
          <th>Departs From</th>
          <th>Arrives</th>
          <th>Miles</th>
          <th>Seats Remaining</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
      <% @flights.each do |flight| %>
        <tr>
          <td><%= flight.number %></td>
          <td>
            <%= flight.departs_at.strftime("%b %d, %Y %H:%M") %>
            <%# Added strftime method %>
          </td>
          <td><%= flight.departure_code %></td>
          <td><%= flight.arrival_code %></td>
          <td><%= flight.distance %></td>
          <td><%= flight.seats %></td>
          <td>
            <% if current_user.present? %>
              <%# Added if statement to prevent user from being able to click to book flights with no seats left. %>
              <% if flight.seats > 0 %>
                <%= form_for @reservation do |f| %>
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <%= f.hidden_field :flight_id, value: flight.id %>

                  <%= f.submit "Book Now", class: 'btn btn-xs btn-primary'%>
                <% end %>
              <% else %>
                <button class="btn btn-xs btn-warning">No Seats Available</button>
              <% end %>
            <% else %>
              <%= link_to "Book Now", new_session_path, notice: "Please log in to book a reservation.", class: 'btn btn-xs btn-primary' %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/flights/new.html.erb
<h1>New Flight</h1>


<%= form_tag(flights_url, method: 'post') do %>


  <div>
    <%= label_tag :departs_at %><br />
    <%= datetime_select_tag :departs_at %>
  </div>

  <div>
    <%= label_tag :departure_code %><br />
    <%= text_field_tag :departure_code %>
  </div>

  <div>
    <%= label_tag :arrival_code %><br />
    <%= text_field_tag :arrival_code %>
  </div>

  <div>
    <%= label_tag :seats %><br />
    <%= number_field_tag :seats %>
  </div>


  <div>
    <%= submit_tag "Create Flight" %>
  </div>
<% end %>

app/views/flights/show.html.erb
<h1>Flight #<%= @flight.id %></h1>

<p>
  <b>Departs at:</b>
  <%= @flight.departs_at %>
</p>

<p>
  <b>Departure code:</b>
  <%= @flight.departure_code %>
</p>

<p>
  <b>Arrival code:</b>
  <%= @flight.arrival_code %>
</p>

<p>
  <b>Seats:</b>
  <%= @flight.seats %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OneWayAir</title>

  <link href="//netdna.bootstrapcdn.com/bootswatch/3.0.0/united/bootstrap.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag 'http://code.jquery.com/ui/1.10.3/themes/cupertino/jquery-ui.css' %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">OneWayAir</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <li>
            <%= link_to flights_url do %>
              &#9992; Flights
              <%# Line 35's airplane symbol is a unicode character and appears here using its HTML code. %>
            <% end %>
          </li>
          <li>
            <%= link_to cities_url do %>
              <i class="icon-building"></i>
              <%# Lines 41 and 48 can use the icon tag and a CSS class to insert symbols from Font Awesome. Font Awesome is linked to in the head tag. %>
              Cities
            <% end %>
          </li>
          <li>
            <%= link_to help_url do %>
              <i class="icon-question-sign"></i>
              Help
            <% end %>
          </li>
          <% unless current_user.present? %>
            <li>
              <%= link_to "Sign Up", new_user_url %>
            </li>
            <li>
              <%= link_to "Sign In", new_session_url %>
            </li>
          <% else %>
            <li>
              <%= link_to "My Profile", user_path(current_user) %>
            </li>
            <li>
              <%= link_to "Sign Out", sessions_url, method: :delete %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">

    <% flash.each do |type, msg| %>
      <div class="alert alert-dismissable alert-<%= type == :notice ? "success" : "error" %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
          &times;
        </button>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/pages/cities.html.erb
    <div class="row">
      <div class="col-med-12">
        <h1 class="page-header">Cities We Serve</h1>
        <table class="table">
          <thead>
            <tr>
              <th>City</th>
              <th>Airport Code</th>
              <th>Information</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Chicago</td>
              <td>ORD</td>
              <td>O'Hare Airport.  4 miles of runway. 400 miles of taxiways.</td>
            </tr>
            <tr>
              <td>Chicago</td>
              <td>MDW</td>
              <td>Midway Airport.  Home of monsters.</td>
            </tr>
            <tr>
              <td>New York</td>
              <td>JFK</td>
              <td>JFK Airport.</td>
            </tr>
            <tr>
              <td>Los Angeles</td>
              <td>LAX</td>
              <td>Los Angeles Airport.</td>
            </tr>
            <tr>
              <td>San Francisco</td>
              <td>SFO</td>
              <td>On the bay.</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <hr>

    <footer>
      <p>&copy;2013 OneWay Airlines</p>
    </footer>
  </div> <!-- /container -->


</body>
</html>

app/views/pages/help.html.erb
<h1 class="page-header">User Stories & Business Rules</h1>

<p>You can skip the challenges if you want, but the user stories should be built in order.</p>

<ol>
  <%= challenge 'Display a nicer date/time in the "Departs At" column' %>
  <%# See index.html.erb for solution. %>
  <%= challenge 'Explain every line in seeds.rb.' %>
  <%# See the seeds file for the line by line explanation. %>
  <%= challenge 'Figure out how the nav links are built with the icons next to them.' %>
  <%# See lines 36 and 42 in the application.html.erb file for icon explanation. %>
  <%= user_story :visitor, 'I want to search by departure airport and date.' %>
  <%= user_story :visitor, 'I want to create a user account so I can sign in.' %>
  <%# Setup user model, sign up logic, sessions controller, sign in, and sign out logic %>
  <%= user_story :user, 'I want to sign in so I can make reservations and earn miles.' %>
  <%# Created reservation join table and associated model relationships. Added functionality to "book now" button. %>
  <%= user_story :user, 'I want to see my profile page listing my reservations and miles earned.' %>
  <%= business_rule "A user's profile page should list all reservations and miles earned." %>
    <%# Added table to user show webpage, miles earned column to users, and custom model method to calculate earned miles. %>
  <%= business_rule 'A user earns miles as soon as they have paid for a reservation, not after they fly' %>
  <%= business_rule 'A user can only book flights if there are seats left on the flight.' %>
  <%= business_rule 'The available seat count must decrease by 1 every time someone books a seat on that flight.' %>
  <%# Added functionality for decrease when booking and increase when cancelling. %>
  <%= user_story :user, 'I want to book a flight.' %>
  <%= business_rule 'A user must pay by credit card when they book a flight, and we only accept Visa.' %>
  <%= business_rule 'Visa cards always start 16 digits long and begin with a 4.' %>

  <%= challenge 'Understand the code for this Help page.' %>
  <%= challenge 'Explain the code in pages_helper.rb' %>
  <%= challenge 'DRY up the code in pages_helper.rb' %>
</ol>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :flight_id %><br>
    <%= f.number_field :flight_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Flight</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.flight_id %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Flight:</strong>
  <%= @reservation.flight_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.present? %>
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Total Miles Earned:</strong>
    <%= @user.miles_earned %>
  </p>

  <p>
    <strong>My Reservations:</strong>
  </p>
  <% if @user.flights.present? %>
    <div class="row">
      <div class="col-md-12">
        <table class='table table-striped'>
          <thead>
            <tr>
              <th>Flight #</th>
              <th>Departs at</th>
              <th>Departs From</th>
              <th>Arrives</th>
              <th>Miles</th>
              <th>Seats Remaining</th>
              <th>Cancel Flight?</th>
            </tr>
          </thead>

          <tbody>
          <% @user.flights.each do |flight| %>
            <tr>
              <td><%= flight.number %></td>
              <td>
                <%= flight.departs_at.strftime("%b %d, %Y %H:%M") %>
              </td>
              <td><%= flight.departure_code %></td>
              <td><%= flight.arrival_code %></td>
              <td><%= flight.distance %></td>
              <td><%= flight.seats %></td>
              <td>
                <%= link_to "Cancel", reservation_path(flight.reservations.first.id), method: "delete", class: 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    <p>No reservations found. Please book some <%= link_to "flights.", root_url %></p>
  <% end %>

  <%= link_to 'Edit My Profile', edit_user_path(@user) %> |
  <%= link_to 'Back To Flight Search', root_url %>

<% end %>